import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";
import Footer from "@/components/Footer/Footer";
import WhatsAppButton from "@/components/WhatsAppButton/WhatsAppButton";
import WhatsAppChat from "@/components/WhatsAppChat/WhatsAppChat";

export const metadata = {
  title: "Decor & Design Interior | Luxury Interior Architecture",
  description: "Modern & Aesthetic Interior Design Solutions"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-scroll-behavior="smooth">
      <body suppressHydrationWarning>
        <Navbar />
        {children}
        <WhatsAppChat />
        <WhatsAppButton />
        <Footer />
      </body>
    </html>
  );
}



























// import Navbar from "@/components/Navbar/Navbar";
// import "./globals.css";

// export const metadata = {
//   title: "Decor & Design Interior | Luxury Interior Architecture",
//   description: "Modern & Aesthetic Interior Design Solutions"
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body suppressHydrationWarning>
//         <Navbar />
//         {children}
//       </body>
//     </html>
//   );
// }

































































// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }
